### ISSUE TITLE
Errors when pressing "Esc" in NPC Chats

### ISSUE THREAD

**Issue by Silwhoon** [doriyan13/SpringStory#18]
When pressing "Esc" here 
![image](https://github.com/doriyan13/SpringStory/assets/29519598/8a2a8ab0-6960-4fe8-829e-b9c16a0bb7c1)

I get the following: 
`[RECEIVED] UserScriptMessageAnswer <65/0x41>: 00 FF 
02/11/2024, 01:50:07 <nioEventLoopGroup-8-1> [NpcHandler]: No message to handle in the ScriptApi for the player - 1`

-------------------------------------------

When pressing "Esc" here
![image](https://github.com/doriyan13/SpringStory/assets/29519598/621d8791-2335-4861-831f-4585a91c8d53)

I get the following:
`[RECEIVED] UserScriptMessageAnswer <65/0x41>: 05 00 
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.dori.SpringStory.connection.netty.ChannelHandler.channelRead0(ChannelHandler.java:107)
	at com.dori.SpringStory.connection.netty.ChannelHandler.channelRead0(ChannelHandler.java:26)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(4) + length(4) exceeds writerIndex(4): UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 4, widx: 4, cap: 4/4)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
	at io.netty.buffer.AbstractByteBuf.readIntLE(AbstractByteBuf.java:817)
	at com.dori.SpringStory.connection.packet.InPacket.decodeInt(InPacket.java:82)
	at com.dori.SpringStory.connection.packet.handlers.NpcHandler.getAskMenuMsgData(NpcHandler.java:67)
	at com.dori.SpringStory.connection.packet.handlers.NpcHandler.handleUserScriptMessageAnswer(NpcHandler.java:134)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 25 more`

**Comment by Silwhoon** [comment]
I believe this happens because NPC scripts are only truly 'cancelled' when "OK" is pressed. If the player presses "NEXT" and there is no other message to send afterwards, this same issue comes up
